### ISSUE TITLE
Setting css in index.css file does not seem to be applied in the samples

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-blazor-examples#371]
1. Refer to the demo from the following section in the docs - https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/combo/overview#styling-blazor-combobox
2. There are styles in css
![image](https://user-images.githubusercontent.com/1182001/234583138-bdeb54c9-0550-45f1-adf3-519dd04cd4df.png)
3. They are not applied to the actual demo

![image](https://user-images.githubusercontent.com/1182001/234583726-8a02b33f-7c82-4466-9208-dac0e252e323.png)

If you review the same sample in Webcomponents you'll notice the styles there are applied correctly https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/combo/overview#styling-web-components-combobox

![image](https://user-images.githubusercontent.com/1182001/234583545-ed3f33d8-3ef6-4e16-98b5-9f1fdc0a402e.png)

**Note:** Not sure why is needed to replace the index.css on the root level, maybe if the samples are importing and using their styles per sample (same for the js files) that could be the solution

**Comment by teodosiah** [comment]
Temporary solution is moving the contents of the index.css files to the App.razor https://github.com/IgniteUI/igniteui-blazor-examples/pull/395

**Comment by HUSSAR-mtrela** [comment]
@teodosiah @dkamburov @zdrawku this issue is fixed on staging. XPLAT samples will have custom CSS exported in index.css files and platform specific samples can define styles either in index.css AND/OR in inline <style> in App.razor files


https://staging.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/combo/overview#styling-blazor-combobox

![image](https://github.com/IgniteUI/igniteui-blazor-examples/assets/11665978/8e2d4a75-bc2e-4f7d-b63e-e6cfe1933747)
